/**
 * Binds the pure engine in `pump-selector.ts` to the real catalogue.
 *
 * The dataset is static JSON generated by `scripts/extract_pump_curves.py` from
 * the PDFs in public/Catalogue and validated by `scripts/verify-pump-curves.mjs`.
 * It lives in the repo rather than the database because it is reference
 * engineering data — it changes only when Kurlar publishes a new catalogue, needs
 * to be reviewable in a diff, and has no admin CRUD. Commercial data (prices,
 * stock) stays in Prisma, joined via `family.productSlug`.
 *
 * Import this from server components only: the JSON is ~600 KB and there is no
 * reason to ship it to the browser, since selection happens during the render.
 */

import curves from "@/data/pump-curves.json";
import kmMotors from "@/data/km-motors.json";
import {
  compatibleMotors,
  findVariant,
  selectPumps,
  type KmMotor,
  type MotorOptions,
  type PumpFamily,
  type PumpVariant,
  type SelectionInput,
  type SelectionResult,
} from "@/lib/pump-selector";

export const PUMP_FAMILIES = curves as PumpFamily[];
export const KM_MOTORS = kmMotors as KmMotor[];

export function selectFromCatalogue(input: SelectionInput): SelectionResult {
  return selectPumps(input, PUMP_FAMILIES);
}

export function motorOptionsFor(variant: PumpVariant): MotorOptions {
  return compatibleMotors(variant, KM_MOTORS);
}

export function findCatalogueVariant(
  code: string,
): { family: PumpFamily; variant: PumpVariant } | null {
  return findVariant(code, PUMP_FAMILIES);
}

/** Widest flow and head the catalogue covers — used for input hints and validation. */
export function catalogueLimits(): {
  maxFlowM3h: number;
  maxHeadM: number;
  minFlowM3h: number;
} {
  let maxFlowM3h = 0;
  let maxHeadM = 0;
  let minFlowM3h = Infinity;
  for (const family of PUMP_FAMILIES) {
    const top = family.flowPointsM3h[family.flowPointsM3h.length - 1];
    if (top > maxFlowM3h) maxFlowM3h = top;
    // The smallest flow any pump can be selected at is the first non-zero
    // breakpoint of the family with the lowest range.
    const firstNonZero = family.flowPointsM3h.find((q) => q > 0);
    if (firstNonZero !== undefined && firstNonZero < minFlowM3h) {
      minFlowM3h = firstNonZero;
    }
    for (const variant of family.variants) {
      for (const head of variant.headsM) {
        if (head !== null && head > maxHeadM) maxHeadM = head;
      }
    }
  }
  return { maxFlowM3h, maxHeadM, minFlowM3h };
}
